spring.application.name=Laboratorio_lex
# --- Configuración de la Base de Datos PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/zone_control_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Configuración del Esquema y Hibernate/JPA ---
spring.jpa.properties.hibernate.default_schema=zone_control
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Configuración de Flyway (Migración de Base de Datos) ---
spring.flyway.enabled=true
spring.flyway.schemas=zone_control
spring.flyway.default-schema=zone_control
spring.flyway.create-schemas=true